---
title: "Ciccolini_Final_Proj"
author: "Skylar Ciccolini"
date: "2025-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Set Up

## Libraries, bring in data, etc
```{r}
library(tidyverse)
library(AICcmodavg)
library(lme4)
library(plotly)
library(gridExtra)
library(see)


# read in data

PF_adult_gridMET_2018_2023_BOI <- read_csv("Data/PF_adult_gridMET_2018_2023_BOI.csv")

# remove NAs
PF_adult_gridMET_2018_2023_BOI <- PF_adult_gridMET_2018_2023_BOI |> 
  filter(!is.na(Restime) & is.finite(Restime))

# read in data

TP_adult_gridMET_2018_2023_BOI <- read_csv("Data/TP_adult_gridMET_2018_2023_BOI.csv")

# remove NAs
TP_adult_gridMET_2018_2023_BOI <- TP_adult_gridMET_2018_2023_BOI %>%
  filter(!is.na(FireTime) & is.finite(FireTime))

# bring in custom theme
manuscript_theme <- list(
  theme_classic(),
  theme(axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "italic", size = 10),
        text = element_text(family = "sans")),
  set.seed(898760))

```

## Models and predictions for Francisella 

```{r}

PF_Fran_Res_climate_int_spp_glm <- glm(data = PF_adult_gridMET_2018_2023_BOI, family = binomial,
                                       FrancisellaPresence ~ Restime*max_temp_summer + Restime*Mean_PDSI + 
                                         max_temp_summer:Mean_PDSI + SPECIES)


TP_Fran_Res_climate_int_spp_glm <- glm(data = TP_adult_gridMET_2018_2023_BOI, family = binomial,
                                       FrancisellaPresence ~ FireTime*max_temp_summer + FireTime*Mean_PDSI + 
                                         max_temp_summer:Mean_PDSI + SPECIES)

####### PFCA


# For A americanum----

# split data by spp

PF_AA <- PF_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "AA")

# predicted values
PF_Fran_Restime_AA_preds <- data.frame(
  Restime = seq(min(PF_AA$Restime), max(PF_AA$Restime), length.out = 100),
  max_temp_summer = mean(PF_AA$max_temp_summer),
  Mean_PDSI = mean(PF_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

PF_Fran_Restime_AA_preds$predicted_prob <- predict(PF_Fran_Res_climate_int_spp_glm, 
                                                newdata = PF_Fran_Restime_AA_preds, type = "response") 

#add std error
PF_Fran_Restime_AA_preds$std_error <- with(PF_Fran_Restime_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Fran_Restime_AA_preds$ci_lower <- PF_Fran_Restime_AA_preds$predicted_prob - 1.96 * PF_Fran_Restime_AA_preds$std_error
PF_Fran_Restime_AA_preds$ci_upper <- PF_Fran_Restime_AA_preds$predicted_prob + 1.96 * PF_Fran_Restime_AA_preds$std_error



# Create a new data frame for predictions
PF_Fran_max_temp_summer_AA_preds <- data.frame(
  Restime = mean(PF_AA$Restime),
  max_temp_summer = seq(min(PF_AA$max_temp_summer), max(PF_AA$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(PF_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
PF_Fran_max_temp_summer_AA_preds$predicted_prob <- predict(PF_Fran_Res_climate_int_spp_glm, 
                                                        newdata = PF_Fran_max_temp_summer_AA_preds, type = "response")

#add std error

PF_Fran_max_temp_summer_AA_preds$std_error <- with(PF_Fran_max_temp_summer_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Fran_max_temp_summer_AA_preds$ci_lower <- PF_Fran_max_temp_summer_AA_preds$predicted_prob - 1.96 * PF_Fran_max_temp_summer_AA_preds$std_error
PF_Fran_max_temp_summer_AA_preds$ci_upper <- PF_Fran_max_temp_summer_AA_preds$predicted_prob + 1.96 * PF_Fran_max_temp_summer_AA_preds$std_error


# Create a new data frame for predictions
PF_Fran_Mean_PDSI_AA_preds <- data.frame(
  Restime = mean(PF_AA$Restime),
  max_temp_summer = mean(PF_AA$max_temp_summer),
  Mean_PDSI = seq(min(PF_AA$Mean_PDSI), max(PF_AA$Mean_PDSI), length.out = 100),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
PF_Fran_Mean_PDSI_AA_preds$predicted_prob <- predict(PF_Fran_Res_climate_int_spp_glm, 
                                                  newdata = PF_Fran_Mean_PDSI_AA_preds, type = "response")
#add std error

PF_Fran_Mean_PDSI_AA_preds$std_error <- with(PF_Fran_Mean_PDSI_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Fran_Mean_PDSI_AA_preds$ci_lower <- PF_Fran_Mean_PDSI_AA_preds$predicted_prob - 1.96 * PF_Fran_Mean_PDSI_AA_preds$std_error
PF_Fran_Mean_PDSI_AA_preds$ci_upper <- PF_Fran_Mean_PDSI_AA_preds$predicted_prob + 1.96 * PF_Fran_Mean_PDSI_AA_preds$std_error

# For D variabilis----

# split data by spp

PF_DV <- PF_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "DV")

# predicted values
PF_Fran_Restime_DV_preds <- data.frame(
  Restime = seq(min(PF_DV$Restime), max(PF_DV$Restime), length.out = 100),
  max_temp_summer = mean(PF_DV$max_temp_summer),
  Mean_PDSI = mean(PF_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

PF_Fran_Restime_DV_preds$predicted_prob <- predict(PF_Fran_Res_climate_int_spp_glm, 
                                                   newdata = PF_Fran_Restime_DV_preds, type = "response") 

#add std error
PF_Fran_Restime_DV_preds$std_error <- with(PF_Fran_Restime_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Fran_Restime_DV_preds$ci_lower <- PF_Fran_Restime_DV_preds$predicted_prob - 1.96 * PF_Fran_Restime_DV_preds$std_error
PF_Fran_Restime_DV_preds$ci_upper <- PF_Fran_Restime_DV_preds$predicted_prob + 1.96 * PF_Fran_Restime_DV_preds$std_error



# Create a new data frame for predictions
PF_Fran_max_temp_summer_DV_preds <- data.frame(
  Restime = mean(PF_DV$Restime),
  max_temp_summer = seq(min(PF_DV$max_temp_summer), max(PF_DV$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(PF_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
PF_Fran_max_temp_summer_DV_preds$predicted_prob <- predict(PF_Fran_Res_climate_int_spp_glm, 
                                                           newdata = PF_Fran_max_temp_summer_DV_preds, type = "response")

#add std error

PF_Fran_max_temp_summer_DV_preds$std_error <- with(PF_Fran_max_temp_summer_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Fran_max_temp_summer_DV_preds$ci_lower <- PF_Fran_max_temp_summer_DV_preds$predicted_prob - 1.96 * PF_Fran_max_temp_summer_DV_preds$std_error
PF_Fran_max_temp_summer_DV_preds$ci_upper <- PF_Fran_max_temp_summer_DV_preds$predicted_prob + 1.96 * PF_Fran_max_temp_summer_DV_preds$std_error


# Create a new data frame for predictions
PF_Fran_Mean_PDSI_DV_preds <- data.frame(
  Restime = mean(PF_DV$Restime),
  max_temp_summer = mean(PF_DV$max_temp_summer),
  Mean_PDSI = seq(min(PF_DV$Mean_PDSI), max(PF_DV$Mean_PDSI), length.out = 100),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
PF_Fran_Mean_PDSI_DV_preds$predicted_prob <- predict(PF_Fran_Res_climate_int_spp_glm, 
                                                     newdata = PF_Fran_Mean_PDSI_DV_preds, type = "response")
#add std error

PF_Fran_Mean_PDSI_DV_preds$std_error <- with(PF_Fran_Mean_PDSI_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Fran_Mean_PDSI_DV_preds$ci_lower <- PF_Fran_Mean_PDSI_DV_preds$predicted_prob - 1.96 * PF_Fran_Mean_PDSI_DV_preds$std_error
PF_Fran_Mean_PDSI_DV_preds$ci_upper <- PF_Fran_Mean_PDSI_DV_preds$predicted_prob + 1.96 * PF_Fran_Mean_PDSI_DV_preds$std_error




####### Tucker

# For A americanum----

# split data by spp

TP_AA <- TP_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "AA")

# predicted values
TP_Fran_FireTime_AA_preds <- data.frame(
  FireTime = seq(min(TP_AA$FireTime), max(TP_AA$FireTime), length.out = 100),
  max_temp_summer = mean(TP_AA$max_temp_summer),
  Mean_PDSI = mean(TP_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

TP_Fran_FireTime_AA_preds$predicted_prob <- predict(TP_Fran_Res_climate_int_spp_glm, 
                                                   newdata = TP_Fran_FireTime_AA_preds, type = "response") 

#add std error
TP_Fran_FireTime_AA_preds$std_error <- with(TP_Fran_FireTime_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Fran_FireTime_AA_preds$ci_lower <- TP_Fran_FireTime_AA_preds$predicted_prob - 1.96 * TP_Fran_FireTime_AA_preds$std_error
TP_Fran_FireTime_AA_preds$ci_upper <- TP_Fran_FireTime_AA_preds$predicted_prob + 1.96 * TP_Fran_FireTime_AA_preds$std_error



# Create a new data frame for predictions
TP_Fran_max_temp_summer_AA_preds <- data.frame(
  FireTime = mean(TP_AA$FireTime),
  max_temp_summer = seq(min(TP_AA$max_temp_summer), max(TP_AA$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(TP_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
TP_Fran_max_temp_summer_AA_preds$predicted_prob <- predict(TP_Fran_Res_climate_int_spp_glm, 
                                                           newdata = TP_Fran_max_temp_summer_AA_preds, type = "response")

#add std error

TP_Fran_max_temp_summer_AA_preds$std_error <- with(TP_Fran_max_temp_summer_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Fran_max_temp_summer_AA_preds$ci_lower <- TP_Fran_max_temp_summer_AA_preds$predicted_prob - 1.96 * TP_Fran_max_temp_summer_AA_preds$std_error
TP_Fran_max_temp_summer_AA_preds$ci_upper <- TP_Fran_max_temp_summer_AA_preds$predicted_prob + 1.96 * TP_Fran_max_temp_summer_AA_preds$std_error


# Create a new data frame for predictions
TP_Fran_Mean_PDSI_AA_preds <- data.frame(
  FireTime = mean(TP_AA$FireTime),
  max_temp_summer = mean(TP_AA$max_temp_summer),
  Mean_PDSI = seq(min(TP_AA$Mean_PDSI), max(TP_AA$Mean_PDSI), length.out = 100),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
TP_Fran_Mean_PDSI_AA_preds$predicted_prob <- predict(TP_Fran_Res_climate_int_spp_glm, 
                                                     newdata = TP_Fran_Mean_PDSI_AA_preds, type = "response")
#add std error

TP_Fran_Mean_PDSI_AA_preds$std_error <- with(TP_Fran_Mean_PDSI_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Fran_Mean_PDSI_AA_preds$ci_lower <- TP_Fran_Mean_PDSI_AA_preds$predicted_prob - 1.96 * TP_Fran_Mean_PDSI_AA_preds$std_error
TP_Fran_Mean_PDSI_AA_preds$ci_upper <- TP_Fran_Mean_PDSI_AA_preds$predicted_prob + 1.96 * TP_Fran_Mean_PDSI_AA_preds$std_error

# For D variabilis----

# split data by spp

TP_DV <- TP_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "DV")

# predicted values
TP_Fran_FireTime_DV_preds <- data.frame(
  FireTime = seq(min(TP_DV$FireTime), max(TP_DV$FireTime), length.out = 100),
  max_temp_summer = mean(TP_DV$max_temp_summer),
  Mean_PDSI = mean(TP_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

TP_Fran_FireTime_DV_preds$predicted_prob <- predict(TP_Fran_Res_climate_int_spp_glm, 
                                                   newdata = TP_Fran_FireTime_DV_preds, type = "response") 

#add std error
TP_Fran_FireTime_DV_preds$std_error <- with(TP_Fran_FireTime_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Fran_FireTime_DV_preds$ci_lower <- TP_Fran_FireTime_DV_preds$predicted_prob - 1.96 * TP_Fran_FireTime_DV_preds$std_error
TP_Fran_FireTime_DV_preds$ci_upper <- TP_Fran_FireTime_DV_preds$predicted_prob + 1.96 * TP_Fran_FireTime_DV_preds$std_error



# Create a new data frame for predictions
TP_Fran_max_temp_summer_DV_preds <- data.frame(
  FireTime = mean(TP_DV$FireTime),
  max_temp_summer = seq(min(TP_DV$max_temp_summer), max(TP_DV$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(TP_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
TP_Fran_max_temp_summer_DV_preds$predicted_prob <- predict(TP_Fran_Res_climate_int_spp_glm, 
                                                           newdata = TP_Fran_max_temp_summer_DV_preds, type = "response")

#add std error

TP_Fran_max_temp_summer_DV_preds$std_error <- with(TP_Fran_max_temp_summer_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Fran_max_temp_summer_DV_preds$ci_lower <- TP_Fran_max_temp_summer_DV_preds$predicted_prob - 1.96 * TP_Fran_max_temp_summer_DV_preds$std_error
TP_Fran_max_temp_summer_DV_preds$ci_upper <- TP_Fran_max_temp_summer_DV_preds$predicted_prob + 1.96 * TP_Fran_max_temp_summer_DV_preds$std_error


# Create a new data frame for predictions
TP_Fran_Mean_PDSI_DV_preds <- data.frame(
  FireTime = mean(TP_DV$FireTime),
  max_temp_summer = mean(TP_DV$max_temp_summer),
  Mean_PDSI = seq(min(TP_DV$Mean_PDSI), max(TP_DV$Mean_PDSI), length.out = 100),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
TP_Fran_Mean_PDSI_DV_preds$predicted_prob <- predict(TP_Fran_Res_climate_int_spp_glm, 
                                                     newdata = TP_Fran_Mean_PDSI_DV_preds, type = "response")
#add std error

TP_Fran_Mean_PDSI_DV_preds$std_error <- with(TP_Fran_Mean_PDSI_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Fran_Mean_PDSI_DV_preds$ci_lower <- TP_Fran_Mean_PDSI_DV_preds$predicted_prob - 1.96 * TP_Fran_Mean_PDSI_DV_preds$std_error
TP_Fran_Mean_PDSI_DV_preds$ci_upper <- TP_Fran_Mean_PDSI_DV_preds$predicted_prob + 1.96 * TP_Fran_Mean_PDSI_DV_preds$std_error






```


## Models and predictions for Rickettsia

```{r}

PF_Rick_Res_climate_int_spp_glm <- glm(data = PF_adult_gridMET_2018_2023_BOI, family = binomial,
                                      RickettsiaPresence ~ Restime*max_temp_summer + Restime*Mean_PDSI + 
                                        max_temp_summer:Mean_PDSI + SPECIES)

TP_Rick_Res_climate_int_spp_glm <- glm(data = TP_adult_gridMET_2018_2023_BOI, family = binomial,
                                       RickettsiaPresence ~ FireTime*max_temp_summer + FireTime*Mean_PDSI + 
                                         max_temp_summer:Mean_PDSI + SPECIES)

###### PFCA

# For A americanum ----

# split data by spp

PF_AA <- PF_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "AA")

# predicted values
PF_Rick_Restime_AA_preds <- data.frame(
  Restime = seq(min(PF_AA$Restime), max(PF_AA$Restime), length.out = 100),
  max_temp_summer = mean(PF_AA$max_temp_summer),
  Mean_PDSI = mean(PF_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

PF_Rick_Restime_AA_preds$predicted_prob <- predict(PF_Rick_Res_climate_int_spp_glm, 
                                                   newdata = PF_Rick_Restime_AA_preds, type = "response") 

#add std error
PF_Rick_Restime_AA_preds$std_error <- with(PF_Rick_Restime_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Rick_Restime_AA_preds$ci_lower <- PF_Rick_Restime_AA_preds$predicted_prob - 1.96 * PF_Rick_Restime_AA_preds$std_error
PF_Rick_Restime_AA_preds$ci_upper <- PF_Rick_Restime_AA_preds$predicted_prob + 1.96 * PF_Rick_Restime_AA_preds$std_error



# Create a new data frame for predictions
PF_Rick_max_temp_summer_AA_preds <- data.frame(
  Restime = mean(PF_AA$Restime),
  max_temp_summer = seq(min(PF_AA$max_temp_summer), max(PF_AA$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(PF_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
PF_Rick_max_temp_summer_AA_preds$predicted_prob <- predict(PF_Rick_Res_climate_int_spp_glm, 
                                                           newdata = PF_Rick_max_temp_summer_AA_preds, type = "response")

#add std error

PF_Rick_max_temp_summer_AA_preds$std_error <- with(PF_Rick_max_temp_summer_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Rick_max_temp_summer_AA_preds$ci_lower <- PF_Rick_max_temp_summer_AA_preds$predicted_prob - 1.96 * PF_Rick_max_temp_summer_AA_preds$std_error
PF_Rick_max_temp_summer_AA_preds$ci_upper <- PF_Rick_max_temp_summer_AA_preds$predicted_prob + 1.96 * PF_Rick_max_temp_summer_AA_preds$std_error


# Create a new data frame for predictions
PF_Rick_Mean_PDSI_AA_preds <- data.frame(
  Restime = mean(PF_AA$Restime),
  max_temp_summer = mean(PF_AA$max_temp_summer),
  Mean_PDSI = seq(min(PF_AA$Mean_PDSI), max(PF_AA$Mean_PDSI), length.out = 100),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
PF_Rick_Mean_PDSI_AA_preds$predicted_prob <- predict(PF_Rick_Res_climate_int_spp_glm, 
                                                     newdata = PF_Rick_Mean_PDSI_AA_preds, type = "response")
#add std error

PF_Rick_Mean_PDSI_AA_preds$std_error <- with(PF_Rick_Mean_PDSI_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Rick_Mean_PDSI_AA_preds$ci_lower <- PF_Rick_Mean_PDSI_AA_preds$predicted_prob - 1.96 * PF_Rick_Mean_PDSI_AA_preds$std_error
PF_Rick_Mean_PDSI_AA_preds$ci_upper <- PF_Rick_Mean_PDSI_AA_preds$predicted_prob + 1.96 * PF_Rick_Mean_PDSI_AA_preds$std_error






# For D variabilis----
# split data by spp

PF_DV <- PF_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "DV")

# predicted values
PF_Rick_Restime_DV_preds <- data.frame(
  Restime = seq(min(PF_DV$Restime), max(PF_DV$Restime), length.out = 100),
  max_temp_summer = mean(PF_DV$max_temp_summer),
  Mean_PDSI = mean(PF_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

PF_Rick_Restime_DV_preds$predicted_prob <- predict(PF_Rick_Res_climate_int_spp_glm, 
                                                   newdata = PF_Rick_Restime_DV_preds, type = "response") 

#add std error
PF_Rick_Restime_DV_preds$std_error <- with(PF_Rick_Restime_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Rick_Restime_DV_preds$ci_lower <- PF_Rick_Restime_DV_preds$predicted_prob - 1.96 * PF_Rick_Restime_DV_preds$std_error
PF_Rick_Restime_DV_preds$ci_upper <- PF_Rick_Restime_DV_preds$predicted_prob + 1.96 * PF_Rick_Restime_DV_preds$std_error



# Create a new data frame for predictions
PF_Rick_max_temp_summer_DV_preds <- data.frame(
  Restime = mean(PF_DV$Restime),
  max_temp_summer = seq(min(PF_DV$max_temp_summer), max(PF_DV$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(PF_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
PF_Rick_max_temp_summer_DV_preds$predicted_prob <- predict(PF_Rick_Res_climate_int_spp_glm, 
                                                           newdata = PF_Rick_max_temp_summer_DV_preds, type = "response")

#add std error

PF_Rick_max_temp_summer_DV_preds$std_error <- with(PF_Rick_max_temp_summer_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Rick_max_temp_summer_DV_preds$ci_lower <- PF_Rick_max_temp_summer_DV_preds$predicted_prob - 1.96 * PF_Rick_max_temp_summer_DV_preds$std_error
PF_Rick_max_temp_summer_DV_preds$ci_upper <- PF_Rick_max_temp_summer_DV_preds$predicted_prob + 1.96 * PF_Rick_max_temp_summer_DV_preds$std_error


# Create a new data frame for predictions
PF_Rick_Mean_PDSI_DV_preds <- data.frame(
  Restime = mean(PF_DV$Restime),
  max_temp_summer = mean(PF_DV$max_temp_summer),
  Mean_PDSI = seq(min(PF_DV$Mean_PDSI), max(PF_DV$Mean_PDSI), length.out = 100),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
PF_Rick_Mean_PDSI_DV_preds$predicted_prob <- predict(PF_Rick_Res_climate_int_spp_glm, 
                                                     newdata = PF_Rick_Mean_PDSI_DV_preds, type = "response")
#add std error

PF_Rick_Mean_PDSI_DV_preds$std_error <- with(PF_Rick_Mean_PDSI_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
PF_Rick_Mean_PDSI_DV_preds$ci_lower <- PF_Rick_Mean_PDSI_DV_preds$predicted_prob - 1.96 * PF_Rick_Mean_PDSI_DV_preds$std_error
PF_Rick_Mean_PDSI_DV_preds$ci_upper <- PF_Rick_Mean_PDSI_DV_preds$predicted_prob + 1.96 * PF_Rick_Mean_PDSI_DV_preds$std_error


###### Tucker

# For A americanum----

# split data by spp

TP_AA <- TP_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "AA")

# predicted values
TP_Rick_FireTime_AA_preds <- data.frame(
  FireTime = seq(min(TP_AA$FireTime), max(TP_AA$FireTime), length.out = 100),
  max_temp_summer = mean(TP_AA$max_temp_summer),
  Mean_PDSI = mean(TP_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

TP_Rick_FireTime_AA_preds$predicted_prob <- predict(TP_Rick_Res_climate_int_spp_glm, 
                                                    newdata = TP_Rick_FireTime_AA_preds, type = "response") 

#add std error
TP_Rick_FireTime_AA_preds$std_error <- with(TP_Rick_FireTime_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Rick_FireTime_AA_preds$ci_lower <- TP_Rick_FireTime_AA_preds$predicted_prob - 1.96 * TP_Rick_FireTime_AA_preds$std_error
TP_Rick_FireTime_AA_preds$ci_upper <- TP_Rick_FireTime_AA_preds$predicted_prob + 1.96 * TP_Rick_FireTime_AA_preds$std_error



# Create a new data frame for predictions
TP_Rick_max_temp_summer_AA_preds <- data.frame(
  FireTime = mean(TP_AA$FireTime),
  max_temp_summer = seq(min(TP_AA$max_temp_summer), max(TP_AA$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(TP_AA$Mean_PDSI),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
TP_Rick_max_temp_summer_AA_preds$predicted_prob <- predict(TP_Rick_Res_climate_int_spp_glm, 
                                                           newdata = TP_Rick_max_temp_summer_AA_preds, type = "response")

#add std error

TP_Rick_max_temp_summer_AA_preds$std_error <- with(TP_Rick_max_temp_summer_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Rick_max_temp_summer_AA_preds$ci_lower <- TP_Rick_max_temp_summer_AA_preds$predicted_prob - 1.96 * TP_Rick_max_temp_summer_AA_preds$std_error
TP_Rick_max_temp_summer_AA_preds$ci_upper <- TP_Rick_max_temp_summer_AA_preds$predicted_prob + 1.96 * TP_Rick_max_temp_summer_AA_preds$std_error


# Create a new data frame for predictions
TP_Rick_Mean_PDSI_AA_preds <- data.frame(
  FireTime = mean(TP_AA$FireTime),
  max_temp_summer = mean(TP_AA$max_temp_summer),
  Mean_PDSI = seq(min(TP_AA$Mean_PDSI), max(TP_AA$Mean_PDSI), length.out = 100),
  SPECIES = rep("AA", 100)
)

# Add predicted probabilities
TP_Rick_Mean_PDSI_AA_preds$predicted_prob <- predict(TP_Rick_Res_climate_int_spp_glm, 
                                                     newdata = TP_Rick_Mean_PDSI_AA_preds, type = "response")
#add std error

TP_Rick_Mean_PDSI_AA_preds$std_error <- with(TP_Rick_Mean_PDSI_AA_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Rick_Mean_PDSI_AA_preds$ci_lower <- TP_Rick_Mean_PDSI_AA_preds$predicted_prob - 1.96 * TP_Rick_Mean_PDSI_AA_preds$std_error
TP_Rick_Mean_PDSI_AA_preds$ci_upper <- TP_Rick_Mean_PDSI_AA_preds$predicted_prob + 1.96 * TP_Rick_Mean_PDSI_AA_preds$std_error


# For D variabilis----

# split data by spp

TP_DV <- TP_adult_gridMET_2018_2023_BOI |> 
  filter(SPECIES == "DV")

# predicted values
TP_Rick_FireTime_DV_preds <- data.frame(
  FireTime = seq(min(TP_DV$FireTime), max(TP_DV$FireTime), length.out = 100),
  max_temp_summer = mean(TP_DV$max_temp_summer),
  Mean_PDSI = mean(TP_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

TP_Rick_FireTime_DV_preds$predicted_prob <- predict(TP_Rick_Res_climate_int_spp_glm, 
                                                    newdata = TP_Rick_FireTime_DV_preds, type = "response") 

#add std error
TP_Rick_FireTime_DV_preds$std_error <- with(TP_Rick_FireTime_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Rick_FireTime_DV_preds$ci_lower <- TP_Rick_FireTime_DV_preds$predicted_prob - 1.96 * TP_Rick_FireTime_DV_preds$std_error
TP_Rick_FireTime_DV_preds$ci_upper <- TP_Rick_FireTime_DV_preds$predicted_prob + 1.96 * TP_Rick_FireTime_DV_preds$std_error



# Create a new data frame for predictions
TP_Rick_max_temp_summer_DV_preds <- data.frame(
  FireTime = mean(TP_DV$FireTime),
  max_temp_summer = seq(min(TP_DV$max_temp_summer), max(TP_DV$max_temp_summer), 
                        length.out = 100),
  Mean_PDSI = mean(TP_DV$Mean_PDSI),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
TP_Rick_max_temp_summer_DV_preds$predicted_prob <- predict(TP_Rick_Res_climate_int_spp_glm, 
                                                           newdata = TP_Rick_max_temp_summer_DV_preds, type = "response")

#add std error

TP_Rick_max_temp_summer_DV_preds$std_error <- with(TP_Rick_max_temp_summer_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Rick_max_temp_summer_DV_preds$ci_lower <- TP_Rick_max_temp_summer_DV_preds$predicted_prob - 1.96 * TP_Rick_max_temp_summer_DV_preds$std_error
TP_Rick_max_temp_summer_DV_preds$ci_upper <- TP_Rick_max_temp_summer_DV_preds$predicted_prob + 1.96 * TP_Rick_max_temp_summer_DV_preds$std_error


# Create a new data frame for predictions
TP_Rick_Mean_PDSI_DV_preds <- data.frame(
  FireTime = mean(TP_DV$FireTime),
  max_temp_summer = mean(TP_DV$max_temp_summer),
  Mean_PDSI = seq(min(TP_DV$Mean_PDSI), max(TP_DV$Mean_PDSI), length.out = 100),
  SPECIES = rep("DV", 100)
)

# Add predicted probabilities
TP_Rick_Mean_PDSI_DV_preds$predicted_prob <- predict(TP_Rick_Res_climate_int_spp_glm, 
                                                     newdata = TP_Rick_Mean_PDSI_DV_preds, type = "response")
#add std error

TP_Rick_Mean_PDSI_DV_preds$std_error <- with(TP_Rick_Mean_PDSI_DV_preds, sd(predicted_prob) / sqrt(length(predicted_prob)))
TP_Rick_Mean_PDSI_DV_preds$ci_lower <- TP_Rick_Mean_PDSI_DV_preds$predicted_prob - 1.96 * TP_Rick_Mean_PDSI_DV_preds$std_error
TP_Rick_Mean_PDSI_DV_preds$ci_upper <- TP_Rick_Mean_PDSI_DV_preds$predicted_prob + 1.96 * TP_Rick_Mean_PDSI_DV_preds$std_error





```


### Manuscript Figures

## Management figs with both bacterias
```{r}
# plot for reconstruction age with both bacterias faceted by SPP ----

# Add a new column to each dataset
PF_Fran_Restime_AA_preds$Pathogen <- "Francisella"
PF_Fran_Restime_AA_preds$Species <- "A. americanum"

PF_Rick_Restime_AA_preds$Pathogen <- "Rickettsia"
PF_Rick_Restime_AA_preds$Species <- "A. americanum"

PF_Fran_Restime_DV_preds$Pathogen <- "Francisella"
PF_Fran_Restime_DV_preds$Species <- "D. variabilis"

PF_Rick_Restime_DV_preds$Pathogen <- "Rickettsia"
PF_Rick_Restime_DV_preds$Species <- "D. variabilis"


# Combine the datasets
PF_paths_combined_preds <- rbind(
  PF_Fran_Restime_AA_preds,
  PF_Rick_Restime_AA_preds,
  PF_Fran_Restime_DV_preds,
  PF_Rick_Restime_DV_preds
)


# Updated ggplot
recon <- ggplot(PF_paths_combined_preds, aes(x = Restime, y = predicted_prob, linetype = Pathogen)) +
  geom_line() +
  geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper), alpha = 0.2) +
  xlab("Reconstruction Year") +
  ylab("Predicted Probability") +
  scale_linetype_manual(
    name = "Pathogen",
    labels = c(expression(italic("Francisella")), expression(italic("Rickettsia"))),
    values = c("Francisella" = "dashed", "Rickettsia" = "solid")
  ) +
  facet_wrap(~Species) +
  manuscript_theme

ggsave("Figs/Recon.jpg", plot = recon, units = "in",
       width = 6, height = 4)

### cant really add raw data because such different y scales of predicted plots and raw data?


# plot for fire with both bacterias

# Add a new column to each dataset
TP_Fran_FireTime_AA_preds$Pathogen <- "Francisella"
TP_Rick_FireTime_AA_preds$Pathogen <- "Rickettsia"

TP_Fran_FireTime_AA_preds$Pathogen <- "Francisella"
TP_Fran_FireTime_AA_preds$Species <- "A. americanum"

TP_Rick_FireTime_AA_preds$Pathogen <- "Rickettsia"
TP_Rick_FireTime_AA_preds$Species <- "A. americanum"

TP_Fran_FireTime_DV_preds$Pathogen <- "Francisella"
TP_Fran_FireTime_DV_preds$Species <- "D. variabilis"

TP_Rick_FireTime_DV_preds$Pathogen <- "Rickettsia"
TP_Rick_FireTime_DV_preds$Species <- "D. variabilis"

# Combine the datasets
TP_paths_combined_preds <- rbind(
  TP_Fran_FireTime_AA_preds,
  TP_Rick_FireTime_AA_preds,
  TP_Fran_FireTime_DV_preds,
  TP_Rick_FireTime_DV_preds
)

# Updated ggplot
fire <- ggplot(TP_paths_combined_preds, aes(x = FireTime, y = predicted_prob, linetype = Pathogen)) +
  geom_line() +
  geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper), alpha = 0.2) +
  xlab("Time Since Fire") +
  ylab("Predicted Probability") +
  scale_linetype_manual(name = "Pathogen", 
                        labels = c(expression(italic("Francisella")),
                                   expression(italic("Rickettsia"))),
                        values = c("Francisella" = "dashed", "Rickettsia" = "solid")) +
  facet_wrap(~SPECIES) +
  manuscript_theme


ggsave("Figs/Fire.jpg", plot = fire, units = "in",
       width = 6, height = 4)


```


## Cliamte figs with both sites with Francisella
```{r}
# plot for max summer temp with both sites----

library(ggplot2)

# Add a new column to each dataset
TP_Fran_max_temp_summer_AA_preds$Site <- "Remnant"
PF_Fran_max_temp_summer_AA_preds$Site <- "Reconstructed"

TP_Fran_max_temp_summer_DV_preds$Site <- "Remnant"
PF_Fran_max_temp_summer_DV_preds$Site <- "Reconstructed"

TP_Fran_max_temp_summer_AA_preds$SPECIES <- "A. americanum"
PF_Fran_max_temp_summer_AA_preds$SPECIES <- "A. americanum"

TP_Rick_max_temp_summer_DV_preds <- "D. variabilis"
PF_Rick_max_temp_summer_DV_preds <- "D. variabilis"

sum <- ggplot() +
  # TP species
  geom_line(data = TP_Fran_max_temp_summer_AA_preds,
            aes(x = max_temp_summer, y = predicted_prob, linetype = Site)) +
  geom_ribbon(data = TP_Fran_max_temp_summer_AA_preds,
              aes(x = max_temp_summer, y = predicted_prob,
                  ymin = ci_lower, ymax = ci_upper, linetype = Site),
              alpha = 0.2) +
  # PF species
  geom_line(data = PF_Fran_max_temp_summer_AA_preds,
            aes(x = max_temp_summer, y = predicted_prob, linetype = Site)) +
  geom_ribbon(data = PF_Fran_max_temp_summer_AA_preds,
              aes(x = max_temp_summer, y = predicted_prob,
                  ymin = ci_lower, ymax = ci_upper, linetype = Site),
              alpha = 0.2) +
  # DV species
  geom_line(data = TP_Fran_max_temp_summer_DV_preds,
            aes(x = max_temp_summer, y = predicted_prob, linetype = Site)) +
  geom_ribbon(data = PF_Fran_max_temp_summer_DV_preds,
              aes(x = max_temp_summer, y = predicted_prob,
                  ymin = ci_lower, ymax = ci_upper, linetype = Site),
              alpha = 0.2) +
  labs(x = expression("Nymphal Questing Max Summer Temperature (" * ~degree * C * ")"),
       y = "Predicted Probability") +
  manuscript_theme +
  facet_wrap(~SPECIES)


ggsave("Figs/Sum.jpg", plot = sum, units = "in",
       width = 6, height = 4)




# plot for pdsi at both study sites ----

# Add a new column to each dataset
TP_Fran_Mean_PDSI_AA_preds$Site <- "Remnant"
PF_Fran_Mean_PDSI_AA_preds$Site <- "Reconstructed"

TP_Fran_Mean_PDSI_DV_preds$Site <- "Remnant"
PF_Fran_Mean_PDSI_DV_preds$Site <- "Reconstructed"

TP_Fran_Mean_PDSI_AA_preds$SPECIES <- "A. americanum"
PF_Fran_Mean_PDSI_AA_preds$SPECIES <- "A. americanum"

TP_Fran_Mean_PDSI_DV_preds$SPECIES <- "D. variabilis"
PF_Fran_Mean_PDSI_DV_preds$SPECIES <- "D. variabilis"


pdsi <- ggplot() +
  # TP species
  geom_line(data = TP_Fran_Mean_PDSI_AA_preds,
            aes(x = Mean_PDSI, y = predicted_prob, linetype = Site)) +
  geom_ribbon(data = TP_Fran_Mean_PDSI_AA_preds,
              aes(x = Mean_PDSI, y = predicted_prob,
                  ymin = ci_lower, ymax = ci_upper, linetype = Site),
              alpha = 0.2) +
  # PF species
  geom_line(data = PF_Fran_Mean_PDSI_AA_preds,
            aes(x = Mean_PDSI, y = predicted_prob, linetype = Site)) +
  geom_ribbon(data = PF_Fran_Mean_PDSI_AA_preds,
              aes(x = Mean_PDSI, y = predicted_prob,
                  ymin = ci_lower, ymax = ci_upper, linetype = Site),
              alpha = 0.2) +
  # DV species
  geom_line(data = TP_Fran_Mean_PDSI_DV_preds,
            aes(x = Mean_PDSI, y = predicted_prob, linetype = Site)) +
  geom_ribbon(data = PF_Fran_Mean_PDSI_DV_preds,
              aes(x = Mean_PDSI, y = predicted_prob,
                  ymin = ci_lower, ymax = ci_upper, linetype = Site),
              alpha = 0.2) +
  labs(x = "PDSI",
       y = "Predicted Probability") +
  manuscript_theme +
  facet_wrap(~SPECIES)


ggsave("Figs/pdsi.jpg", plot = pdsi, units = "in",
       width = 6, height = 4)






```


### Oral Presentation Figure

```{r}
# map of field sites

library(ggmap)

# create map with prairie locs
locs <- tribble(~ lat, ~ lon, ~ ID,
                -91.7408, 38.8922, "Prairie Fork",
                -91.9902, 38.949, "Tucker")

# Create bounding box for locations
sbbox <- make_bbox(lon = locs$lon,
                   lat = locs$lat,
                   f = 0.25) # Expansion factor

# Download map
sq_map <- get_stamenmap(bbox = sbbox,
                        maptype = "terrain")

p <- ggmap(sq_map) + 
  geom_point(data = Locations,
             mapping = aes(x = lon, y = lat),
             color = "red",
             size = 3) +
  labs(x = "Longitude", y = "Latitude")
p


p +
  annotate(geom = "text",
           x = -92.45,
           y = 39.35,
           label = "Field Sites on the Missouri River",
           size = 8) +
  geom_text_repel(data = Locations,
                  mapping = aes(x = lon, y = lat, label = ID),
                  box.padding = 1,
                  seed = 431579)

# create map of US




# combine as inset
```



### Poster Presentation Figure

## PFCA positivity
```{r}

# plot for francisella positive cases over years
PF_Fran_pos <- PF_adult_gridMET_2018_2023_BOI |> 
  group_by(YEAR) |> 
  summarise(positives = sum(FrancisellaPresence),
            total = n())

PF_Fran_pos <- PF_Fran_pos |> 
  mutate(percent = (positives/total) * 100)



PF_Fran_pos <- ggplot() +
  geom_col(data = PF_Fran_pos, aes(x = YEAR, y = total), fill = "grey80") +
  geom_col(data = PF_Fran_pos, aes(x = YEAR, y = positives), fill = "red") +
  geom_text(data = PF_Fran_pos,
            aes(x = YEAR, y = positives, label = paste0(round(percent, 1), "%")),
            vjust = -0.5, fontface = "bold", color = "black") +
  labs(x = "Year", y = "Ticks Collected") +
  manuscript_theme

ggsave("Figs/PF_Fran_pos.jpg", plot = PF_Fran_pos, units = "in",
       width = 6, height = 4)

# plot for rickettsia presence over years
PF_Rick_pos <- PF_adult_gridMET_2018_2023_BOI |> 
  group_by(YEAR) |> 
  summarise(positives = sum(RickettsiaPresence),
            total = n())

PF_Rick_pos <- PF_Rick_pos |> 
  mutate(percent = (positives/total) * 100)



PF_Rick_pos <- ggplot() +
  geom_col(data = PF_Rick_pos, aes(x = YEAR, y = total), fill = "grey80") +
  geom_col(data = PF_Rick_pos, aes(x = YEAR, y = positives), fill = "red") +
  geom_text(data = PF_Rick_pos,
            aes(x = YEAR, y = positives, label = paste0(round(percent, 1), "%")),
            vjust = -0.5, fontface = "bold", color = "black") +
  labs(x = "Year", y = "Ticks Collected") +
  manuscript_theme ### probably should denote positives somehow

ggsave("Figs/PF_rick_pos.jpg", plot = PF_Rick_pos, units = "in",
       width = 6, height = 4)
```













